---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2 on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"
  - name: start webserver on ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"

  - name: install apache2 on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"
  - name: start webserver on redhat
    service:
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"  
