---
- hosts: webservers
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2 on ubuntu
    apt:
      name: "{{webserverpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: start webserver on ubuntu
    service:
      name: "{{webserverpackonubuntu}}"
      state: started
    when: ansible_os_family =="Debian"
  - name: install apache2 on redhat(httpd)
    yum:
      name: "{{webserverpackonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: start webserver on redhat
    service:
      name: "{{webserverpackonredhat}}"
      state: started
    when: ansible_os_family =="RedHat" 
    
    
  - name: remove git
    apt:
       name: "{{mygit}}"
       state: absent
    when: ansible_os_family=="Debain"